// .examples/react/app.jsx
import React, { useState, useCallback, useRef } from 'react';
import { Formast } from '../../src/react';
import schemaJson from '../_shared/form.json';
import { isEmpty } from 'ts-fns';
import * as Options from '../../src/react-d/index.js';

export default function App() {
  const [errors, setErrors] = useState([]);
  const [data, setData] = useState({});
  const [random, setRandom] = useState(Math.random());
  const ref = useRef();

  const handleSubmit = useCallback((e) => {
    e.preventDefault();

    const errors = ref.current.validate();
    if (errors.length) {
      setErrors(errors);
      setData({});
      return;
    }

    const data = ref.current.toData();
    setErrors([]);
    setData(data);
  }, []);

  const getJson = () => new Promise((r) => {
    setTimeout(() => r(schemaJson), 2000);
  });

  return (
    <div>
      <Formast
        schema={getJson}
        props={{
          onSubmit: handleSubmit,
          random: random,
        }}
        options={Options}
        onLoad={({ model }) => {
          ref.current = model;
          window.__model = model;
        }}
      >
        <span>正在加载...</span>
      </Formast>
      <div>
        {errors.map((err, i) => {
          return <div key={i} style={{ color: 'red' }}>{err.message}</div>
        })}
      </div>
      <pre>
        {isEmpty(data) ? null : JSON.stringify(data, null, 4)}
      </pre>
      <button onClick={() => setRandom(Math.random())}>Random</button>
    </div>
  );
}

// .examples/vue/app.vue
<template>
  <div>
    <formast :schema="getJson" :props="props" :onLoad="onLoad" :options="options">
      <span>正在加载...</span>
    </formast>
    <div>
      <div v-for="err,i in errors" :key="i" style="color:red">{{err.message}}</div>
    </div>
    <pre>{{data}}</pre>
    <button type="button" @click="handleRadom">Random</button>
  </div>
</template>

<script>
import schemaJson from '../_shared/form.json';
import { Formast } from '../../src/vue';
import * as Options from '../../src/vue-d/index.js';

export default {
  data() {
    return {
      data: null,
      errors: [],
      model: null,
      props: {
        random: Math.random(),
        onSubmit: this.handleSubmit,
      },
      options: Options,
    }
  },
  methods: {
    handleSubmit(e) {
      e.preventDefault();

      const errors = this.model.validate();
      if (errors.length) {
        this.errors = errors;
        this.data = null;
        return;
      }

      this.errors = [];
      const data = this.model.toData();
      this.data = data;
    },
    handleRadom() {
      this.props.random = Math.random()
    },
    getJson() {
      return new Promise((r) => {
        setTimeout(() => r(schemaJson), 2000)
      })
    },
    onLoad({ model }) {
      this.model = model;
    },
  },
  components: {
    Formast,
  },
}
</script>
